# Generated by Django 4.0.4 on 2022-04-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=10, null=True)),
                ('othernames', models.CharField(max_length=10, null=True)),
                ('accountnumber', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
            ],
        ),
    ]
