# Generated by Django 4.0.4 on 2023-02-02 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='account',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='witdrawal',
            name='account',
        ),
        migrations.RemoveField(
            model_name='witdrawal',
            name='staff',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Witdrawal',
        ),
    ]
