# Generated by Django 4.0.4 on 2022-08-12 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_deposit_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer'),
        ),
    ]
