# Generated by Django 4.0.4 on 2023-03-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='transID',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
