# Generated by Django 4.0.4 on 2023-02-03 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customer_fee_rename_staff_profile_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='customer',
            new_name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
    ]
