# Generated by Django 4.0.4 on 2023-03-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_deposit_transid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witdrawal',
            name='transID',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
