# Generated by Django 4.0.4 on 2023-02-03 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_account_rename_user_profile_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
    ]
