# Generated by Django 4.0.4 on 2023-02-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_deposit_acct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='acct',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
